# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Notifications' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AWSCognito'
  pod 'AWSDynamoDB'
  pod 'AWSS3'

end

target 'NotificationImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AWSCognito'
  pod 'AWSDynamoDB'
  pod 'AWSS3'

end
